theme = "rose_pine"

# [editor]
# # end-of-line-diagnostics = "hint"
# [editor.inline-diagnostics]
# cursor-line = "warning" # show warnings and errors on the cursorline inline

# [editor.indent-guides]
# render = true
# character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 0

# [editor.lsp]
# display-inlay-hints = false
[editor]
true-color = true
#line-number = "relative"
cursorline = true
bufferline = "multiple"
mouse = true
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
